In [58]:
import csv
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
questions = pd.read_csv('questions.csv')
question_tags = pd.read_csv('question_tags.csv')

In [11]:
questions.head(10)

,Id,CreationDate,ClosedDate,DeletionDate,Score,OwnerUserId,AnswerCount
0,1,2008-07-31T21:26:37Z,NaN,2011-03-28T00:53:47Z,1,NaN,0.0
1,4,2008-07-31T21:42:52Z,NaN,NaN,458,8.0,13.0
2,6,2008-07-31T22:08:08Z,NaN,NaN,207,9.0,5.0
3,8,2008-07-31T23:33:19Z,2013-06-03T04:00:25Z,2015-02-11T08:26:40Z,42,NaN,8.0
4,9,2008-07-31T23:40:59Z,NaN,NaN,1410,1.0,58.0
5,11,2008-07-31T23:55:37Z,NaN,NaN,1129,1.0,33.0
6,13,2008-08-01T00:42:38Z,NaN,NaN,451,9.0,25.0
7,14,2008-08-01T00:59:11Z,NaN,NaN,290,11.0,8.0
8,16,2008-08-01T04:59:33Z,NaN,NaN,78,2.0,5.0
9,17,2008-08-01T05:09:55Z,NaN,NaN,114,2.0,11.0

In [28]:
question_tags.head(12)

    Id                  Tag
0    1                 data
1    4                   c#
2    4             winforms
3    4      type-conversion
4    4              decimal
5    4              opacity
6    6                 html
7    6                  css
8    6                 css3
9    6  internet-explorer-7
10   8                   c#
11   8      code-generation

Want dataframe of each tag by the "creation date" of related question

In [25]:
join = question_tags.merge(questions, left_on='Id', right_on='Id', how='outer')

In [30]:
tags_by_creation_date = join[['Tag','CreationDate']]

In [35]:
sorted_tags_by_creation_date = tags_by_creation_date.sort_values(by=['Tag'])
sorted_tags_by_creation_date.head(100)

                         Tag          CreationDate
2461788                    #  2010-07-22T21:59:27Z
2199495                 #-+-  2010-06-11T11:34:29Z
202071                     +  2009-01-05T04:37:16Z
190430              -session  2008-12-23T14:32:21Z
207109                 -test  2009-01-07T19:45:34Z
295124    ..................  2009-02-22T04:58:58Z
295125    ..................  2009-02-22T04:59:18Z
40898351                  .a  2016-01-28T15:53:11Z
42828283                  .a  2016-04-07T14:47:50Z
40901915                  .a  2016-01-28T17:51:38Z
26252511                  .a  2014-06-15T01:32:17Z
37168817                  .a  2015-08-31T23:10:33Z
28677137                  .a  2014-09-25T08:54:18Z
10159065                  .a  2012-06-01T22:37:20Z
15201974                  .a  2013-03-08T11:05:42Z
5214209                   .a  2011-06-02T08:01:25Z
46830801                  .a  2016-09-07T15:52:10Z
33585434                  .a  2015-04-15T12:56:52Z
20837699                  .a  2013-11-14T11:09:55Z
41173222                  .a  2016-02-08T12:08:06Z
35682323                  .a  2015-07-04T18:26:18Z
50202320                  .a  2017-01-22T08:24:25Z
9848001                   .a  2012-05-14T04:46:28Z
31964957                  .a  2015-02-11T21:22:27Z
26305649                  .a  2014-06-17T12:58:26Z
35787197                  .a  2015-07-08T18:32:05Z
18130364                  .a  2013-07-19T11:44:56Z
1443458                   .a  2010-01-28T20:14:23Z
30154454                  .a  2014-11-25T11:36:12Z
11488529                  .a  2012-08-20T20:56:03Z
...                      ...                   ...
46193945                  .a  2016-08-12T09:34:56Z
37534036                  .a  2015-09-15T16:19:25Z
34334469                  .a  2015-05-13T17:08:06Z
34784569                  .a  2015-05-31T14:07:13Z
34731146                  .a  2015-05-28T22:44:07Z
37332250                  .a  2015-09-07T16:03:45Z
36301700                  .a  2015-07-28T15:24:40Z
48810632                  .a  2016-11-24T14:51:36Z
25297545                  .a  2014-05-07T06:11:25Z
5756560                   .a  2011-07-19T02:40:53Z
29556463                  .a  2014-10-31T23:25:40Z
34369781                  .a  2015-05-14T21:34:24Z
5969846                   .a  2011-08-04T19:44:40Z
1723679                   .a  2010-03-21T19:27:00Z
17479742                  .a  2013-06-20T04:50:54Z
34562185                  .a  2015-05-22T08:18:49Z
39013532                  .a  2015-11-12T15:04:25Z
33196135                  .a  2015-03-31T07:57:38Z
17983635                  .a  2013-07-12T21:20:35Z
5270804                   .a  2011-06-07T15:45:24Z
38221698                  .a  2015-10-13T07:48:37Z
20936280                  .a  2013-11-18T18:38:00Z
8834897                   .a  2012-03-11T12:51:40Z
5169183                   .a  2011-05-29T10:03:36Z
42982449                  .a  2016-04-13T08:04:09Z
50243124                  .a  2017-01-23T23:40:52Z
34536017                  .a  2015-05-21T10:58:22Z
24633681                  .a  2014-04-11T00:31:30Z
24982707                  .a  2014-04-24T14:02:47Z
39432916                  .a  2015-11-29T07:20:28Z

[100 rows x 2 columns]

In [32]:
tags_by_creation_date.shape

(50576842, 2)

In [36]:
tags_by_creation_date.dtypes

Tag             object
CreationDate    object
dtype: object

In [39]:
tags_by_creation_date_2017 = tags_by_creation_date[(tags_by_creation_date['CreationDate'] >= '2017-01-01')]

In [75]:
tags_by_creation_date_2017.Tag.value_counts(dropna=False)[301:400]

promise                     366
filter                      364
ruby-on-rails-5             364
phpmyadmin                  364
ffmpeg                      363
input                       362
react-redux                 361
groovy                      358
.net-core                   358
terminal                    357
automation                  355
django-models               355
time                        354
cmake                       354
vscode                      353
highcharts                  351
methods                     350
serialization               350
winapi                      349
printing                    347
razor                       347
twitter                     346
nullpointerexception        343
google-analytics            343
vuejs2                      341
login                       340
react-router                339
bluetooth                   336
paypal                      335
select                      335
                           ...
datepicker                  295
keras                       293
realm                       293
awk                         292
rust                        292
sed                         292
replace                     290
dll                         290
dependency-injection        290
makefile                    289
error-handling              289
asp.net-mvc-5               288
firebase-cloud-messaging    288
dplyr                       286
pagination                  286
datagridview                285
merge                       285
build                       285
compiler-errors             284
youtube                     284
tcp                         284
docker-compose              284
mvvm                        282
url-rewriting               280
dynamic                     278
oauth                       278
mongodb-query               278
hash                        278
scrapy                      278
electron                    275
Name: Tag, Length: 99, dtype: int64

Try to plot just one tag over year 2017

In [79]:
#electron = tags_by_creation_date_2017[tags_by_creation_date_2017['Tag'] == 'electron']
electron = tags_by_creation_date[tags_by_creation_date['Tag'] == 'electron']

In [89]:
tags_by_creation_date['CreationDate_DateTime'] = pd.to_datetime(tags_by_creation_date['CreationDate'])
tags_by_creation_date.head()

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

               Tag          CreationDate CreationDate_DateTime
0             data  2008-07-31T21:26:37Z   2008-07-31 21:26:37
1               c#  2008-07-31T21:42:52Z   2008-07-31 21:42:52
2         winforms  2008-07-31T21:42:52Z   2008-07-31 21:42:52
3  type-conversion  2008-07-31T21:42:52Z   2008-07-31 21:42:52
4          decimal  2008-07-31T21:42:52Z   2008-07-31 21:42:52

In [90]:
tags_by_creation_date.head()

               Tag          CreationDate CreationDate_DateTime
0             data  2008-07-31T21:26:37Z   2008-07-31 21:26:37
1               c#  2008-07-31T21:42:52Z   2008-07-31 21:42:52
2         winforms  2008-07-31T21:42:52Z   2008-07-31 21:42:52
3  type-conversion  2008-07-31T21:42:52Z   2008-07-31 21:42:52
4          decimal  2008-07-31T21:42:52Z   2008-07-31 21:42:52

In [98]:
# Get frequency of each distinct tag
tags_by_frequency_dict = tags_by_creation_date.Tag.value_counts(dropna=False)
tags_by_frequency_dict

javascript               1649631
java                     1563820
php                      1365600
c#                       1321027
android                  1288338
jquery                   1011324
python                    854172
html                      776512
ios                       635227
c++                       627341
mysql                     561375
css                       545587
sql                       436546
asp.net                   400619
objective-c               338539
ruby-on-rails             325003
c                         306418
.net                      301454
iphone                    274464
angularjs                 267560
arrays                    250864
json                      232047
sql-server                226410
r                         212482
ruby                      210152
ajax                      207908
linux                     201748
node.js                   200239
xml                       193305
asp.net-mvc               183981
                          ...
kmeans                         1
architect                      1
moss2007                       1
one-time-pad                   1
text-to-image                  1
raw-packets                    1
node-scss                      1
webtatic                       1
autorefresh                    1
associative-arrays             1
password-management            1
messagesource                  1
dancing-links                  1
shoryuken                      1
fgl                            1
xamarin-android                1
drugs                          1
seminar                        1
uipagesviewcontroller          1
javascript-6                   1
blah                           1
gldatepicker                   1
wm8350                         1
re-use                         1
jquery1.3.2                    1
remodel                        1
change.org                     1
technology-agonostic           1
gtsd                           1
react-flexbox-grid             1
Name: Tag, Length: 58256, dtype: int64

In [97]:
tags_by_frequency_dict.shape

(58256,)

Find the median and then the lowest 5% of occurences by tag frequency

In [108]:
tags_by_frequency_dict[tags_by_frequency_dict.apply(lambda x: x==1)]

model-format                1
httpurirequest              1
project-type                1
should-be-on-serverfault    1
emea                        1
duvet                       1
control-adapters            1
html-entity-decode          1
testapp                     1
php-framework               1
libhybris                   1
sendall                     1
gmsl                        1
perl-ppm                    1
groovy-ldap                 1
caret-position              1
connection-providers        1
assumption                  1
telerik-radscheduler        1
sexy                        1
cubemap                     1
eql                         1
windows-hacking             1
oreilly                     1
fpcalc                      1
sprint.ly                   1
application-templates       1
uiwebview-afnetworking      1
oms                         1
clobs                       1
                           ..
kmeans                      1
architect                   1
moss2007                    1
one-time-pad                1
text-to-image               1
raw-packets                 1
node-scss                   1
webtatic                    1
autorefresh                 1
associative-arrays          1
password-management         1
messagesource               1
dancing-links               1
shoryuken                   1
fgl                         1
xamarin-android             1
drugs                       1
seminar                     1
uipagesviewcontroller       1
javascript-6                1
blah                        1
gldatepicker                1
wm8350                      1
re-use                      1
jquery1.3.2                 1
remodel                     1
change.org                  1
technology-agonostic        1
gtsd                        1
react-flexbox-grid          1
Name: Tag, Length: 7989, dtype: int64

In [110]:
sorted_tags = tags_by_creation_date.sort_values(by=['Tag'])
sorted_tags.head()

              Tag          CreationDate CreationDate_DateTime
2461788         #  2010-07-22T21:59:27Z   2010-07-22 21:59:27
2199495      #-+-  2010-06-11T11:34:29Z   2010-06-11 11:34:29
202071          +  2009-01-05T04:37:16Z   2009-01-05 04:37:16
190430   -session  2008-12-23T14:32:21Z   2008-12-23 14:32:21
207109      -test  2009-01-07T19:45:34Z   2009-01-07 19:45:34

In [112]:
reactjs = sorted_tags[sorted_tags['Tag'] == 'reactjs']
reactjs.sort_values(by=['CreationDate_DateTime'], inplace=True)
reactjs

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

              Tag          CreationDate CreationDate_DateTime
16804123  reactjs  2013-05-20T03:44:25Z   2013-05-20 03:44:25
17048682  reactjs  2013-05-30T23:05:17Z   2013-05-30 23:05:17
17530941  reactjs  2013-06-22T07:41:16Z   2013-06-22 07:41:16
17586711  reactjs  2013-06-25T10:18:46Z   2013-06-25 10:18:46
17879855  reactjs  2013-07-09T00:06:11Z   2013-07-09 00:06:11
17937287  reactjs  2013-07-11T05:37:07Z   2013-07-11 05:37:07
18942264  reactjs  2013-08-25T10:06:32Z   2013-08-25 10:06:32
19186312  reactjs  2013-09-05T04:30:21Z   2013-09-05 04:30:21
19249431  reactjs  2013-09-08T03:51:49Z   2013-09-08 03:51:49
19333765  reactjs  2013-09-11T18:58:28Z   2013-09-11 18:58:28
19360683  reactjs  2013-09-12T17:54:49Z   2013-09-12 17:54:49
19365082  reactjs  2013-09-12T21:47:34Z   2013-09-12 21:47:34
19501531  reactjs  2013-09-19T04:14:52Z   2013-09-19 04:14:52
19535460  reactjs  2013-09-20T09:43:08Z   2013-09-20 09:43:08
19560455  reactjs  2013-09-21T14:50:46Z   2013-09-21 14:50:46
19659640  reactjs  2013-09-25T20:06:06Z   2013-09-25 20:06:06
19959268  reactjs  2013-10-08T22:12:18Z   2013-10-08 22:12:18
19967419  reactjs  2013-10-09T07:57:36Z   2013-10-09 07:57:36
20052132  reactjs  2013-10-12T15:06:36Z   2013-10-12 15:06:36
20079780  reactjs  2013-10-14T09:50:49Z   2013-10-14 09:50:49
20094385  reactjs  2013-10-14T21:21:37Z   2013-10-14 21:21:37
20631653  reactjs  2013-11-06T09:13:34Z   2013-11-06 09:13:34
20664412  reactjs  2013-11-07T11:22:05Z   2013-11-07 11:22:05
20813429  reactjs  2013-11-13T14:38:47Z   2013-11-13 14:38:47
20832946  reactjs  2013-11-14T07:48:38Z   2013-11-14 07:48:38
20908806  reactjs  2013-11-17T17:01:32Z   2013-11-17 17:01:32
21086098  reactjs  2013-11-24T13:25:19Z   2013-11-24 13:25:19
21183740  reactjs  2013-11-28T00:51:31Z   2013-11-28 00:51:31
21329075  reactjs  2013-12-04T09:30:55Z   2013-12-04 09:30:55
21336975  reactjs  2013-12-04T14:23:07Z   2013-12-04 14:23:07
...           ...                   ...                   ...
50568999  reactjs  2017-02-05T14:35:07Z   2017-02-05 14:35:07
50569201  reactjs  2017-02-05T14:51:00Z   2017-02-05 14:51:00
50569760  reactjs  2017-02-05T15:31:13Z   2017-02-05 15:31:13
50569898  reactjs  2017-02-05T15:40:03Z   2017-02-05 15:40:03
50570522  reactjs  2017-02-05T16:19:13Z   2017-02-05 16:19:13
50570733  reactjs  2017-02-05T16:30:08Z   2017-02-05 16:30:08
50571217  reactjs  2017-02-05T17:03:56Z   2017-02-05 17:03:56
50571720  reactjs  2017-02-05T17:39:43Z   2017-02-05 17:39:43
50571762  reactjs  2017-02-05T17:43:02Z   2017-02-05 17:43:02
50571967  reactjs  2017-02-05T17:58:39Z   2017-02-05 17:58:39
50572021  reactjs  2017-02-05T18:01:18Z   2017-02-05 18:01:18
50572199  reactjs  2017-02-05T18:14:10Z   2017-02-05 18:14:10
50572450  reactjs  2017-02-05T18:30:55Z   2017-02-05 18:30:55
50572816  reactjs  2017-02-05T18:54:28Z   2017-02-05 18:54:28
50572962  reactjs  2017-02-05T19:06:02Z   2017-02-05 19:06:02
50573027  reactjs  2017-02-05T19:10:01Z   2017-02-05 19:10:01
50573085  reactjs  2017-02-05T19:12:16Z   2017-02-05 19:12:16
50573768  reactjs  2017-02-05T19:55:21Z   2017-02-05 19:55:21
50574726  reactjs  2017-02-05T21:04:36Z   2017-02-05 21:04:36
50575175  reactjs  2017-02-05T21:38:14Z   2017-02-05 21:38:14
50575701  reactjs  2017-02-05T22:15:05Z   2017-02-05 22:15:05
50575986  reactjs  2017-02-05T22:39:42Z   2017-02-05 22:39:42
50575994  reactjs  2017-02-05T22:40:21Z   2017-02-05 22:40:21
50576019  reactjs  2017-02-05T22:42:18Z   2017-02-05 22:42:18
50576168  reactjs  2017-02-05T22:54:19Z   2017-02-05 22:54:19
50576293  reactjs  2017-02-05T23:05:42Z   2017-02-05 23:05:42
50576466  reactjs  2017-02-05T23:21:10Z   2017-02-05 23:21:10
50576477  reactjs  2017-02-05T23:21:31Z   2017-02-05 23:21:31
50576674  reactjs  2017-02-05T23:45:18Z   2017-02-05 23:45:18
50576724  reactjs  2017-02-05T23:50:59Z   2017-02-05 23:50:59

[38162 rows x 3 columns]

In [127]:
#reactjs_CreationDate_DateTime = reactjs['CreationDate_DateTime']
#reactjs_CreationDate_DateTime.CreationDate_DateTime = pd.to_datetime(reactjs_CreationDate_DateTime.CreationDate_DateTime, unit='s')
reactjs.CreationDate_DateTime = pd.to_datetime(reactjs.CreationDate_DateTime, unit='s')

/anaconda3/lib/python3.6/site-packages/pandas/core/generic.py:3110: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value

In [120]:
reactjs_CreationDate_DateTime

1970-07-14 11:48:43    2013-05-20T03:44:25Z
1970-07-17 07:44:42    2013-05-30T23:05:17Z
1970-07-22 21:42:21    2013-06-22T07:41:16Z
1970-07-23 13:11:51    2013-06-25T10:18:46Z
1970-07-26 22:37:35    2013-07-09T00:06:11Z
1970-07-27 14:34:47    2013-07-11T05:37:07Z
1970-08-08 05:44:24    2013-08-25T10:06:32Z
1970-08-11 01:31:52    2013-09-05T04:30:21Z
1970-08-11 19:03:51    2013-09-08T03:51:49Z
1970-08-12 18:29:25    2013-09-11T18:58:28Z
1970-08-13 01:58:03    2013-09-12T17:54:49Z
1970-08-13 03:11:22    2013-09-12T21:47:34Z
1970-08-14 17:05:31    2013-09-19T04:14:52Z
1970-08-15 02:31:00    2013-09-20T09:43:08Z
1970-08-15 09:27:35    2013-09-21T14:50:46Z
1970-08-16 13:00:40    2013-09-25T20:06:06Z
1970-08-20 00:14:28    2013-10-08T22:12:18Z
1970-08-20 02:30:19    2013-10-09T07:57:36Z
1970-08-21 02:02:12    2013-10-12T15:06:36Z
1970-08-21 09:43:00    2013-10-14T09:50:49Z
1970-08-21 13:46:25    2013-10-14T21:21:37Z
1970-08-27 19:00:53    2013-11-06T09:13:34Z
1970-08-28 04:06:52    2013-11-07T11:22:05Z
1970-08-29 21:30:29    2013-11-13T14:38:47Z
1970-08-30 02:55:46    2013-11-14T07:48:38Z
1970-08-31 00:00:06    2013-11-17T17:01:32Z
1970-09-02 01:14:58    2013-11-24T13:25:19Z
1970-09-03 04:22:20    2013-11-28T00:51:31Z
1970-09-04 20:44:35    2013-12-04T09:30:55Z
1970-09-04 22:56:15    2013-12-04T14:23:07Z
                               ...
1971-08-09 06:56:39    2017-02-05T14:35:07Z
1971-08-09 07:00:01    2017-02-05T14:51:00Z
1971-08-09 07:09:20    2017-02-05T15:31:13Z
1971-08-09 07:11:38    2017-02-05T15:40:03Z
1971-08-09 07:22:02    2017-02-05T16:19:13Z
1971-08-09 07:25:33    2017-02-05T16:30:08Z
1971-08-09 07:33:37    2017-02-05T17:03:56Z
1971-08-09 07:42:00    2017-02-05T17:39:43Z
1971-08-09 07:42:42    2017-02-05T17:43:02Z
1971-08-09 07:46:07    2017-02-05T17:58:39Z
1971-08-09 07:47:01    2017-02-05T18:01:18Z
1971-08-09 07:49:59    2017-02-05T18:14:10Z
1971-08-09 07:54:10    2017-02-05T18:30:55Z
1971-08-09 08:00:16    2017-02-05T18:54:28Z
1971-08-09 08:02:42    2017-02-05T19:06:02Z
1971-08-09 08:03:47    2017-02-05T19:10:01Z
1971-08-09 08:04:45    2017-02-05T19:12:16Z
1971-08-09 08:16:08    2017-02-05T19:55:21Z
1971-08-09 08:32:06    2017-02-05T21:04:36Z
1971-08-09 08:39:35    2017-02-05T21:38:14Z
1971-08-09 08:48:21    2017-02-05T22:15:05Z
1971-08-09 08:53:06    2017-02-05T22:39:42Z
1971-08-09 08:53:14    2017-02-05T22:40:21Z
1971-08-09 08:53:39    2017-02-05T22:42:18Z
1971-08-09 08:56:08    2017-02-05T22:54:19Z
1971-08-09 08:58:13    2017-02-05T23:05:42Z
1971-08-09 09:01:06    2017-02-05T23:21:10Z
1971-08-09 09:01:17    2017-02-05T23:21:31Z
1971-08-09 09:04:34    2017-02-05T23:45:18Z
1971-08-09 09:05:24    2017-02-05T23:50:59Z
Name: CreationDate, Length: 38162, dtype: object